pub const DEFAULT_WINDOW_WIDTH: i32 = 600;
pub const DEFAULT_WINDOW_HEIGHT: i32 = 400;

pub const DEFAULT_FILL_PERCENTAGE: u8 = 90;
pub const DEFAULT_FIRE_BASE_HEIGHT: usize = 20;
pub const DEFAULT_COOLING_LENGTH_SCALE: f64 = 0.02;
pub const DEFAULT_COOLING_STRENGTH: f64 = 0.10;